name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Ensure Dockerfile exists (fallback)
        run: |
          mkdir -p infrastructure
          if [ ! -f infrastructure/Dockerfile ]; then
            echo "⚠️ Dockerfile nicht gefunden – Erzeuge Fallback..."
            cat <<EOF > infrastructure/Dockerfile
FROM nginx:alpine
COPY . /usr/share/nginx/html
EOF
          else
            echo "✅ Dockerfile ist bereits vorhanden."
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_HILL_00BD9E103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"              # HTML liegt direkt im Root
          api_location: "api"            # Functions in /api
          output_location: "/"           # Kein Build notwendig

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_HILL_00BD9E103 }}
          action: "close"
