name: Trigger auto deployment for webshopcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/webshopcontainerapp-AutoDeployTrigger-4fb5165f-f346-4448-ae17-af4695313680.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBSHOPCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBSHOPCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBSHOPCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.WEBSHOPCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBSHOPCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: webshopcontainerapp
          resourceGroup: webshop-rg
          imageToBuild: JonasDacode/webshopcontainerapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


